# Generated by Django 5.1.15 on 2026-06-02 22:13

import django.db.models.deletion
import talent.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveSmallIntegerField(default=18)),
                ('category', models.CharField(db_index=True, max_length=80)),
                ('display_category', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(db_index=True, max_length=80)),
                ('country', models.CharField(default='', max_length=80)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('mini_bio', models.TextField(max_length=280)),
                ('extended_bio', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('experience', models.JSONField(blank=True, default=list)),
                ('goals', models.JSONField(blank=True, default=list)),
                ('availability', models.CharField(choices=[('immediate', 'Immediate'), ('part-time', 'Part-time'), ('not-available', 'Not available')], db_index=True, default='immediate', max_length=20)),
                ('is_validated', models.BooleanField(db_index=True, default=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('overall_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('technical_stats', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('audio', 'Audio')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='portfolio/')),
                ('external_url', models.URLField(blank=True, max_length=500)),
                ('order_index', models.PositiveSmallIntegerField(validators=[talent.validators.validate_order_index])),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='talent.profile')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('external_url', models.URLField(blank=True, max_length=500)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_tracks', to='talent.profile')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('like', 'Like'), ('pass', 'Pass'), ('bookmark', 'Bookmark')], db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['sender', 'receiver', 'action_type'], name='talent_conn_sender__c99c9a_idx'), models.Index(fields=['receiver', 'action_type', '-created_at'], name='talent_conn_receive_00cda1_idx')],
                'constraints': [models.UniqueConstraint(fields=('sender', 'receiver', 'action_type'), name='unique_connection_per_action')],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_one', to=settings.AUTH_USER_MODEL)),
                ('user_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_two', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user_one', '-created_at'], name='talent_matc_user_on_c21f8b_idx'), models.Index(fields=['user_two', '-created_at'], name='talent_matc_user_tw_d4d67a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_one', 'user_two'), name='unique_match_pair')],
            },
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['category', 'availability'], name='talent_prof_categor_a80b86_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['city', 'is_validated'], name='talent_prof_city_29ef9c_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['latitude', 'longitude'], name='talent_prof_latitud_d90276_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['profile', 'order_index'], name='talent_medi_profile_1b9155_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['media_type'], name='talent_medi_media_t_37b9cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.UniqueConstraint(fields=('profile', 'order_index'), name='unique_media_order_per_profile'),
        ),
        migrations.AddIndex(
            model_name='audiotrack',
            index=models.Index(fields=['profile', 'order_index'], name='talent_audi_profile_60fc9a_idx'),
        ),
    ]
